language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
os:
    - windows
    - linux
before_install:
    - git clone https://github.com/php/pecl-caching-wincache.git
    - cd wincache && sudo ./configure && sudo make check && sudo make install && cd ..
install:
    - pecl channel-update pecl.php.net
    - pecl install wincache
    - travis_retry composer install --no-interaction
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
    - chmod +x php-coveralls.phar
    - php php-coveralls.phar --version
after_success:
    - travis_retry php php-coveralls.phar -v
before_script:
    - mkdir -p build/logs
    - ls -al
script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
